export const skills = [
  {
    id: 1,
    name: "JAVASCRIPT",
    color: "yellow",
    logo: "Javascript",
    logoColor: "ffffff",
  },
  {
    id: 2,
    name: "TYPESCRIPT",
    color: "3178C6",
    logo: "TypeScript",
    logoColor: "ffffff",
  },
  {
    id: 3,
    name: "JEST.JS",
    color: "C21325",
    logo: "Jest",
    logoColor: "ffffff",
  },
  {
    id: 4,
    name: "GRAPHQL",
    color: "E10098",
    logo: "GraphQl",
    logoColor: "ffffff",
  },
  {
    id: 5,
    name: "VUE.JS",
    color: "4FC08D",
    logo: "vuedotjs",
    logoColor: "ffffff",
  },
  {
    id: 6,
    name: "VUETIFY",
    color: "1867C0",
    logo: "Vuetify",
    logoColor: "ffffff",
  },
  {
    id: 7,
    name: "NUXT.JS",
    color: "00C58E",
    logo: "nuxtdotjs",
    logoColor: "ffffff",
  },
  {
    id: 8,
    name: "NEXT.JS",
    color: "000000",
    logo: "nextdotjs",
    logoColor: "ffffff",
  },
  {
    id: 9,
    name: "REACT.JS",
    color: "61DAFB",
    logo: "React",
    logoColor: "ffffff",
  },
  {
    id: 10,
    name: "SASS",
    color: "CC6699",
    logo: "Sass",
    logoColor: "ffffff",
  },
  {
    id: 11,
    name: "BOOTSTRAP",
    color: "7952B3",
    logo: "bootstrap",
    logoColor: "ffffff",
  },
  {
    id: 12,
    name: "TAILWIND",
    color: "38B2AC",
    logo: "Tailwind-CSS",
    logoColor: "ffffff",
  },
];

export const tools = [
  {
    id: 1,
    name: "GIT",
    color: "F05032",
    logo: "Git",
    logoColor: "ffffff",
  },
  {
    id: 2,
    name: "VERCEL",
    color: "000000",
    logo: "Vercel",
    logoColor: "ffffff",
  },
  {
    id: 3,
    name: "NETLIFY",
    color: "00C7B7",
    logo: "Netlify",
    logoColor: "ffffff",
  },
  {
    id: 4,
    name: "POSTMAN",
    color: "FF6C37",
    logo: "Postman",
    logoColor: "ffffff",
  },
];
